run:
  issues-exit-code: 1
  allow-parallel-runners: true

  skip-dirs:
    - "api"

linters:
  enable-all: true
  disable:
    # deprecated
    - scopelint
    - golint
    - interfacer
    - maligned
    - exhaustivestruct
    - structcheck
    - varcheck
    - deadcode
    - ifshort
    - nosnakecase
    - tagalign
    - depguard
    - dupl
    - exhaustruct
    - revive
    - stylecheck
    # irrelevant
    - goerr113
    # using goimports-reviser
    - gci

issues:
  fix: true
  exclude-rules:
    - linters:
        - lll
      source: '"https://github.com/gost1k337/url_shortener|//'

linters-settings:
  lll:
    line-length: 120
  varnamelen:
    min-name-length: 1

