basePath: /.
host: localhost:10000
info:
  contact: {}
  description: This is a REST API service for creating short urls.
  title: Url Shortener
  version: "1.0"
paths:
  /short:
    post:
      description: Create short url from url and return it
      operationId: create-short-url
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create short url
      tags:
      - ShortURL
  /u/{token}:
    get:
      description: Redirect user from short url to original url
      operationId: redirect-short-url
      responses:
        "303":
          description: See Other
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Redirect to original url
      tags:
      - ShortURL
  /users:
    post:
      description: Create user
      operationId: create-user
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create user
      tags:
      - User
  /users/{id}:
    delete:
      description: Delete user
      operationId: delete-user
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete user
      tags:
      - User
    get:
      description: Get user
      operationId: get-user
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get user
      tags:
      - User
swagger: "2.0"
