version: "3"

services:
  postgres:
    container_name: us_postgres
    image: postgres:15.4
    networks:
      - url_short_network
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .docker.env
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 3s
      retries: 5

  url_shortening_service:
    container_name: url_shortening_service
    build: .
    networks:
      - url_short_network
    volumes:
      - ./logs:/logs
    env_file:
      - .docker.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    networks:
      - url_short_network
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "${POSTGRES_DSN}", "up" ]
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

networks:
  url_short_network:
    external: true
volumes:
  pg-data: