name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  service:

jobs:
  golangci:
    strategy:
      matrix:
        go: [ '1.21' ]
        os: [ macos-latest ]
        service:
          - api_gateway_service
          - url_shortening_service
          - user_service
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Run golangci-lint for ${{ matrix.service }}
        with:
          version: v1.54
        run: |
          cd ${{ matrix.service }}
          golangci-lint run
          env:
          GO111MODULE: on
