name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  service:

jobs:
  golangci:
    strategy:
      matrix:
        go: [ '1.21' ]
        os: [ macos-latest ]
        workdir: [user_service, api_gateway_service, url_shortening_service]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Lint ${{ matrix.workdir }}
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          working_directory: ${{ matrix.workdir }}
