name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  service:

jobs:
  golangci:
    strategy:
      matrix:
        go: [ '1.21' ]
        os: [ macos-latest ]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Lint user_service
        run: |
          ls
          cd ./user_service
          golangci-lint run
        working-directory: ./user_service
        env:
          GO111MODULE: on
      - name: Lint url_shortening_service
        run: |
          ls
          cd ./url_shortening_service
          golangci-lint run
        working-directory: ./url_shortening_service
        env:
          GO111MODULE: on
      - name: Lint api_gateway_service
        run: |
          ls
          cd ./api_gateway_service
          golangci-lint run
        working-directory: ./api_gateway_service
        env:
          GO111MODULE: on
